"DOTAAbilities"
{
  // Shields a random friendly unit with energy, giving it +2 armor. The next time
  // the unit is hit by a negative building ability, the ability will have no
  // effect and the shield will vanish.

  // Shields a random friendly unit with energy, giving it +4 armor. The next two
  // times the unit is hit by a negative building ability, the ability will have
  // no effect. In addition, the unit will gain +100 health.
  "generator_energy_shield"
  {
    "AbilityTextureName"          "abaddon_aphotic_shield"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/energy_shield"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
    "AbilityCooldown"             "1.0"
    "AbilityManaCost"             "7"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_medusa/medusa_mana_shield.vpcf"
      "soundfile" "soundevents/game_sounds.vsndevts"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"           "FIELD_INTEGER"
        "armor"              "2 4"
      }
      "02"
      {
        "var_type"           "FIELD_INTEGER"
        "initial_stacks"     "1 2"
      }
    }
  }

  "energy_tower_bouncing_attack"
  {
    "AbilityTextureName"          "luna_moon_glaive"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/naga/bouncing_attack"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"          "FIELD_INTEGER"
        "range"             "500"
      }
      "02"
      {
        "var_type"          "FIELD_INTEGER"
        "bounces"           "3"
      }
      "03"
      {
        "var_type"                  "FIELD_INTEGER"
        "damage_reduction_percent"  "30"
      }
    }
  }

  "energy_tower_energy_burst"
  {
    "AbilityTextureName"             "harpy_storm_chain_lightning"
    "BaseClass"                      "ability_lua"
    "ScriptFile"                     "abilities/human/passive_chain_lightning"
    "MaxLevel"                       "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    "AbilityUnitDamageType"       "DAMAGE_TYPE_MAGICAL"

    "precache"
    {
      "particle"  "particles/items_fx/chain_lightning.vpcf"
      "soundfile" "soundevents/game_sounds_items.vsndevts"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"               "FIELD_INTEGER"
        "trigger_chance"         "20"
      }
      "02"
      {
        "var_type"           "FIELD_INTEGER"
        "initial_damage"     "80"
      }
      "03"
      {
        "var_type"           "FIELD_INTEGER"
        "max_targets"        "8"
      }
      "04"
      {
        "var_type"                 "FIELD_FLOAT"
        "jump_damage_reduction"    "0.20"
      }
      "05"
      {
        "var_type"           "FIELD_INTEGER"
        "jump_range"         "500"
      }
      "06"
      {
        "var_type"           "FIELD_FLOAT"
        "jump_delay"         "0.25"
      }
    }
  }

  // Assembles a Gobbo Mechanist every 25 seconds, which lasts 40 seconds and looks for
  // damaged buildings and mechanical units it can repair
  "assemble_gobbo_mechanist"
  {
    "AbilityTextureName"          "tinker_march_of_the_machines"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/assemble_gobbo_mechanist"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
    "AbilityCooldown"             "1.0"
    "AbilityManaCost"             "25"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"           "FIELD_INTEGER"
        "duration"           "40"
      }
    }
  }

  // Powers all buildings in 180 range, giving them +2 armor.
  // Empowered buildings have a chance to get negative buffs removed from them.
  // In addition, towers gain +25%% damage and special buildings gain +0.25 mana/sec.
  // Creep producing structures train stronger creeps.
  //   - 100 bonus HP
  //   - 2 bonus Armor
  //   - 20%% bonus damage
  "power_buildings"
  {
    "AbilityTextureName"          "tinker_rearm"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/power_buildings"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityCastRange"        "180"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"              "FIELD_INTEGER"
        "radius"                "200"
      }
      "02"
      {
        "var_type"              "FIELD_INTEGER"
        "armor"                 "2"
      }
      "03"
      {
        "var_type"              "FIELD_INTEGER"
        "tower_damage"          "25"
      }
      "04"
      {
        "var_type"              "FIELD_FLOAT"
        "mana_regen"            "0.25"
      }
      "05"
      {
        "var_type"              "FIELD_INTEGER"
        "creep_health"          "100"
      }
      "06"
      {
        "var_type"              "FIELD_INTEGER"
        "creep_armor"           "2"
      }
      "07"
      {
        "var_type"              "FIELD_INTEGER"
        "creep_damage"          "20"
      }
    }
  }

  "gyrocopter_bash"
  {
    "AbilityTextureName"          "gyrocopter_flak_cannon"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/generic/bash"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    "AbilityUnitDamageType"       "DAMAGE_TYPE_MAGICAL"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"       "FIELD_FLOAT"
        "bash_duration"  "1.2"
      }
      "02"
      {
        "var_type"       "FIELD_INTEGER"
        "bash_chance"    "30 50"
      }
      "03"
      {
        "var_type"       "FIELD_INTEGER"
        "bash_damage"    "45 60"
      }
    }
  }

  "adamant_golem_bash"
  {
    "AbilityTextureName"          "rattletrap_battery_assault"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/generic/bash"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    "AbilityUnitDamageType"       "DAMAGE_TYPE_MAGICAL"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"       "FIELD_FLOAT"
        "bash_duration"  "2.0"
      }
      "02"
      {
        "var_type"       "FIELD_INTEGER"
        "bash_chance"    "15 50"
      }
      "03"
      {
        "var_type"       "FIELD_INTEGER"
        "bash_damage"    "40 150"
      }
    }
  }

  "tank_armor"
  {
    "AbilityTextureName"          "shredder_reactive_armor"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/generic/damage_reduction"
    "MaxLevel"                    "3"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"          "FIELD_INTEGER"
        "damage_reduced"    "12 18 24"
      }
      "02"
      {
        "var_type"          "FIELD_INTEGER"
        "reduction_chance"  "100"
      }
    }
  }

  // Fires rockets at random enemies in 850 range. Each rocket deals 75 damage
  // mana cost 0, cd ??, num targets ??
  "rocket_tank_aa_rockets"
  {
    "AbilityTextureName"          "tinker_heat_seeking_missile"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/aa_rockets"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityCastRange"          "850"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_tinker/tinker_missile.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_tinker.vsndevts"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"      "FIELD_INTEGER"
        "damage"        "75"
      }
      "02"
      {
        "var_type"    "FIELD_INTEGER"
        "radius"      "850"
      }
    }
  }

  // Lay a mine that explodes when enemies walk on top of it.
  // Deals 250 damage to enemies in 150 range, and 125 damage to enemies in 300 range
  "mine_layer_lay_mine"
  {
    "AbilityTextureName"          "techies_land_mines"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/lay_mine"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET"

    "AbilityCooldown"             "14.0"
    "AbilityManaCost"             "40"

    "AbilityCastPoint"          "0.1"
    "AbilityCastAnimation"      "ACT_DOTA_CAST_ABILITY_4"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_techies/techies_land_mine_explode.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_techies.vsndevts"
      "model" "models/heroes/techies/fx_techiesfx_mine.vmdl"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"      "FIELD_INTEGER"
        "damage"        "125"
      }
      "02"
      {
        "var_type"         "FIELD_INTEGER"
        "close_radius"     "150"
      }
      "03"
      {
        "var_type"         "FIELD_INTEGER"
        "far_radius"       "300"
      }
    }
  }

  // (275 dmg) 275 in 150 aoe, 125 in 300 aoe, buildings take 75%
  "lunatic_goblin_suicide"
  {
    "AbilityTextureName"          "techies_suicide"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/suicide"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET"

    "AbilityCooldown"             "30.0"
    "AbilityManaCost"             "0"

    "AbilityCastPoint"          "0.1"

    "AbilityCastRange"        "300"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_techies/techies_suicide.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_techies.vsndevts"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"      "FIELD_INTEGER"
        "full_damage"   "275"
      }
      "02"
      {
        "var_type"         "FIELD_INTEGER"
        "close_radius"     "150"
      }
      "03"
      {
        "var_type"         "FIELD_INTEGER"
        "far_radius"       "300"
      }
      "04"
      {
        "var_type"      "FIELD_INTEGER"
        "far_damage"    "125"
      }
    }
  }

  // Upon death, does 150 to enemies in 280 aoe, further targets take less damage,
  // stacks with suicide
  "lunatic_goblin_detonate"
  {
    "AbilityTextureName"          "techies_focused_detonate"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/detonate"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityCastRange"        "280"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"      "FIELD_INTEGER"
        "radius"        "280"
      }
      "02"
      {
        "var_type"         "FIELD_INTEGER"
        "damage"           "150"
      }
    }
  }

  // hits all units 150 range behind its attacks
  "flamegunner_line_damage"
  {
    "AbilityTextureName"          "dragon_knight_breathe_fire"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/elf/line_damage"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                   "FIELD_INTEGER"
        "attack_spill_range"         "200"
      }
      "02"
      {
        "var_type"                   "FIELD_INTEGER"
        "attack_spill_width"         "350"
      }
    }
  }

  // Launches a grenade that deals 30 damage and burns up to 100 mana, dealing
  // mana burned as damage. Slows units by 50%% for 3 seconds. 300 AoE
  "flamegunner_astral_grenade"
  {
    "AbilityTextureName"          "antimage_mana_void"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/astral_grenade"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
    "AbilityUnitTargetTeam"       "DOTA_UNIT_TARGET_TEAM_ENEMY"
    "AbilityUnitTargetType"       "DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"

    "AbilityCooldown"             "15"
    "AbilityManaCost"             "0"

    "AbilityCastRange"          "600"
    "AbilityCastPoint"          "0.3"
    "AbilityCastAnimation"      "ACT_DOTA_CAST_ABILITY_1"

    "precache"
    {
      "particle"  "particles/econ/items/antimage/antimage_weapon_basher_ti5/antimage_manavoid_ti_5.vpcf"
      "particle"  "particles/generic_gameplay/generic_manaburn.vpcf"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"      "FIELD_INTEGER"
        "damage"          "30"
      }
      "02"
      {
        "var_type"      "FIELD_INTEGER"
        "mana_burn"     "100"
      }
      "03"
      {
        "var_type"      "FIELD_INTEGER"
        "move_slow"     "50"
      }
      "04"
      {
        "var_type"          "FIELD_INTEGER"
        "slow_duration"     "3"
      }
      "05"
      {
        "var_type"          "FIELD_INTEGER"
        "radius"            "300"
      }
    }
  }

  "iron_golem_spell_resistance"
  {
    "AbilityTextureName"          "rattletrap_power_cogs"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/spell_resistance"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                   "FIELD_INTEGER"
        "magic_resistance"           "30 65"
      }
      "02"
      {
        "var_type"                   "FIELD_INTEGER"
        "status_resistance"          "30 90"
      }
    }
  }

  "adamant_golem_pulverize"
  {
    "AbilityTextureName"          "earthshaker_enchant_totem"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/generic/pulverize"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/econ/items/earthshaker/earthshaker_arcana/earthshaker_arcana_aftershock_v2.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_earthshaker.vsndevts"
    }

    "AbilitySpecial"
    {
       "01"
      {
        "var_type"      "FIELD_INTEGER"
        "chance"        "25 40"
      }
      "02"
      {
        "var_type"      "FIELD_INTEGER"
        "close_range"   "150"
      }
      "03"
      {
        "var_type"      "FIELD_INTEGER"
        "close_damage"  "60 150"
      }
      "04"
      {
        "var_type"      "FIELD_INTEGER"
        "far_range"     "250"
      }
      "05"
      {
        "var_type"      "FIELD_FLOAT"
        "far_damage"    "30 75"
      }
    }
  }

  // Each time the shredder is hit by a negative special building, it permanently
  // gains 50%% attackspeed and has a 60%% chance to block the spell's effect.
  // Attack speed bonus is capped at 200%%
  "goblin_shredder_inducted_rage"
  {
    "AbilityTextureName"          "shredder_reactive_armor"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/inducted_rage"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"               "FIELD_INTEGER"
        "block_chance"           "60"
      }
      "02"
      {
        "var_type"              "FIELD_INTEGER"
        "attack_speed"          "50"
      }
      "03"
      {
        "var_type"              "FIELD_INTEGER"
        "max_stacks"            "4"
      }
    }
  }

  // Upon death, the shredder deals up to 50 damage to enemies in 300 range.
  // Each time the shredder gets hit by a negative special building the damage
  // gets doubled. Max of 4 hits.
  "goblin_shredder_detonate"
  {
    "AbilityTextureName"          "techies_focused_detonate"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/detonate"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityCastRange"        "300"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"        "FIELD_INTEGER"
        "base_damage"     "50"
      }
      "02"
      {
        "var_type"        "FIELD_INTEGER"
        "max_stacks"      "4"
      }
      "03"
      {
        "var_type"        "FIELD_INTEGER"
        "radius"          "300"
      }
    }
  }

  // each hit does full damage to units in 160 range in front of this unit
  "goblin_shredder_attack"
  {
    "AbilityTextureName"          "shredder_timber_chain"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/mech/shredder_attack"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"         "FIELD_INTEGER"
        "radius"           "160"
      }
    }
  }
}