"DOTAAbilities"
{
  // Deals 10 dps to all non-mechanical enemy units. Does not stack.
  "city_of_decay_decay"
  {
    "AbilityTextureName"          "undying_decay"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/decay"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityValues"
    {
      "dps"                     "8"
    }
  }

  // has a 5% chance to steal the soul of the unit it attacks,
  // instantly killing it.
  "turret_of_souls_soul_steal"
  {
    "AbilityTextureName"          "necrolyte_death_pulse"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/soul_steal"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityValues"
    {
      "chance"                  "5"
    }
  }

  // Reduces the armor of nearby enemy units by 3
  "weaken_soul"
  {
    "AbilityTextureName"          "nevermore_dark_lord"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/weaken_soul"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    "AbilityCastRange"            "400"

    "AbilityValues"
    {
      "armor_reduction"         "3"
      "range"                   "800"
    }
  }

  // Raises a random skeleton from a random corpse
  "skull_pile_raise_dead"
  {
    "AbilityTextureName"          "dark_troll_warlord_raise_dead"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/raise_dead"
    "MaxLevel"                    "1"

    "precache"
    {
      "particle"  "particles/econ/items/necrolyte/necro_sullen_harvest/necro_ti7_immortal_scythe_impact.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts"
    }

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
    "AbilityCooldown"             "1.0"
    "AbilityManaCost"             "12"
  }

  "skull_shrine_greater_raise_dead"
  {
    "AbilityTextureName"          "dark_troll_warlord_raise_dead"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/raise_dead"
    "MaxLevel"                    "1"

    "precache"
    {
      "particle"  "particles/econ/items/necrolyte/necro_sullen_harvest/necro_ti7_immortal_scythe_impact.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts"
    }

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
    "AbilityCooldown"             "1.0"
    "AbilityManaCost"             "15"
  }

  // Raises a skeleton
  "necromancer_raise_dead"
  {
    "AbilityTextureName"          "dark_troll_warlord_raise_dead"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/raise_dead"
    "MaxLevel"                    "1"

    "precache"
    {
      "particle"  "particles/econ/items/necrolyte/necro_sullen_harvest/necro_ti7_immortal_scythe_impact.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts"
    }

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET"
    "AbilityCooldown"             "45.0"
    "AbilityManaCost"             "75"

    "AbilityCastRange"          "900"
    "AbilityCastPoint"          "0.5"
    "AbilityCastAnimation"      "ACT_DOTA_CAST_ABILITY_1"
  }

  // Raises a skeleton. Can also raise Greater Skeletons and Heros. (but no generals)
  "necromancer_greater_raise_dead"
  {
    "AbilityTextureName"          "dark_troll_warlord_raise_dead"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/raise_dead"
    "MaxLevel"                    "1"

    "precache"
    {
      "particle"  "particles/econ/items/necrolyte/necro_sullen_harvest/necro_ti7_immortal_scythe_impact.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts"
    }

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET"
    "AbilityCooldown"             "30.0"
    "AbilityManaCost"             "75"

    "AbilityCastRange"          "900"
    "AbilityCastPoint"          "0.5"
    "AbilityCastAnimation"      "ACT_DOTA_CAST_ABILITY_1"
  }

  // Raises 2 greater skeletons. Skeletons raised this way have 3 bonus armor and 12 bonus damage.
  // Cooldown 25, Mana Cost 100
  "lich_ultimate_raise_dead"
  {
    "AbilityTextureName"          "dark_troll_warlord_raise_dead"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/raise_dead"
    "MaxLevel"                    "1"

    "precache"
    {
      "particle"  "particles/econ/items/necrolyte/necro_sullen_harvest/necro_ti7_immortal_scythe_impact.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts"
    }

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET"
    "AbilityCooldown"             "25.0"
    "AbilityManaCost"             "100"

    "AbilityCastRange"          "900"
    "AbilityCastPoint"          "0.5"
    "AbilityCastAnimation"      "ACT_DOTA_CAST2_STATUE"

    "AbilityValues"
    {
      "armor_bonus"      "3"
      "damage_bonus"    "12"
    }
  }

  // Kills a random enemy unit instantly
  "sudden_death"
  {
    "AbilityTextureName"          "necrolyte_death_pulse"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/sudden_death"
    "MaxLevel"                    "1"

    "precache"
    {
      "particle"  "particles/custom/undead/death_pit/sudden_death.vpcf"
      "particle"  "particles/units/heroes/hero_techies/techies_remote_mines_detonate.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_bloodseeker.vsndevts"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_techies.vsndevts"
    }

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
    "AbilityCooldown"             "1.0"
    "AbilityManaCost"             "20.0"
  }

  // Damages organic enemies in range, dealing damage per second
  "zombie_rot"
  {
    "AbilityTextureName"          "pudge_rot"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/zombie_rot"
    "MaxLevel"                    "3"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_pudge/pudge_rot.vpcf"
      "particle"  "particles/units/heroes/hero_pudge/pudge_rot_recipient.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_pudge.vsndevts"
    }

    "AbilityValues"
    {
      "dps"                     "8 12 20"
      "radius"                  "250 290 350"
    }
  }

  // Units hit by the Zombie get their ms reduced by 15% and receive 8
  // dps for 10 seconds
  "zombie_plague_attack"
  {
    "AbilityTextureName"          "undying_soul_rip"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/plague_attack"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_venomancer/venomancer_poison_debuff.vpcf"
    }

    "AbilityValues"
    {
      "dps"                     "8 15"
      "move_speed_slow_pct"     "15 30"
      "duration"                "10 15"
    }
  }

  // 25% chance on attack to release a carrion swarm that deals
  // 70 damage to all enemies in a cone.
  "necromancer_carrion_swarm"
  {
    "AbilityTextureName"          "death_prophet_carrion_swarm"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/carrion_swarm"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/econ/items/death_prophet/death_prophet_acherontia/death_prophet_acher_swarm.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_death_prophet.vsndevts"
    }

    "AbilityValues"
    {
      "chance"                  "25"
      "damage"                  "70"
      "start_radius"            "110"
      "end_radius"              "300"
      "range"                   "810"
      "speed"                   "1100"
    }
  }

  // Has a 15% chance to soul steal its target, killing it instantly and
  // gaining 50% of its health, or a 10% chance to cast Death and Decay
  // onto a 300 aoe around its target.
  //
  // Death and Decay lasts 5 seconds, drains 8% of enemy's max health per
  // second
  "lich_decaying_attack"
  {
    "AbilityTextureName"          "necrolyte_heartstopper_aura"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/decaying_attack"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/econ/items/necrolyte/necro_ti9_immortal/necro_ti9_immortal_shroud.vpcf"
      "soundfile" "game_sounds_necrolyte.vsndevts"
    }

    "AbilityValues"
    {
      "soul_steal_chance"       "15"
      "soul_steal_absorb"       "50"
      "death_and_decay_chance"  "10"
      "death_and_decay_aoe"      "300"
      "death_and_decay_duration" "5"
      "damage_percent"          "8"
    }
  }

  "raise_lesser_vampire"
  {
    "AbilityTextureName"          "night_stalker_hunter_in_the_night"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/raise_vampire"
    "MaxLevel"                    "1"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_night_stalker/nightstalker_loadout_bats.vpcf"
      "particle"  "particles/units/heroes/hero_night_stalker/nightstalker_void.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_nightstalker.vsndevts"
    }

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
  }

  "raise_vampire"
  {
    "AbilityTextureName"          "night_stalker_hunter_in_the_night"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/raise_vampire"
    "MaxLevel"                    "1"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_night_stalker/nightstalker_loadout_bats.vpcf"
      "particle"  "particles/units/heroes/hero_night_stalker/nightstalker_void.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_nightstalker.vsndevts"
    }

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
  }

  "vampire_lifesteal_aura"
  {
    "AbilityTextureName"          "life_stealer_feast"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/lifesteal_aura"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    "AbilityCastRange"            "900"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_skeletonking/wraith_king_vampiric_aura_lifesteal.vpcf"
    }

    "AbilityValues"
    {
      "radius"        "900"
      "lifesteal"     "20 35"
    }
  }

  // Decreases the damage output of all enemies in 450 range by 15%
  "banshee_fear_aura"
  {
    "AbilityTextureName"          "arc_warden_spark_wraith"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/fear_aura"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    "AbilityCastRange"            "450"

    "AbilityValues"
    {
      "radius"         "450"
      "damage_decrease"    "15"
    }
  }

  // Reduces movement and attack speed of target enemy by 30% for 35 seconds.
  // 10 cd 25 mana
  "banshee_astral_chains"
  {
    "AbilityTextureName"          "visage_grave_chill"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/astral_chains"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
    "AbilityUnitTargetTeam"       "DOTA_UNIT_TARGET_TEAM_ENEMY"
    "AbilityUnitTargetType"       "DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"

    "AbilityCooldown"             "10.0"
    "AbilityManaCost"             "25"

    "AbilityCastRange"        "700"
    "AbilityCastPoint"        "0.3"
    "AbilityCastAnimation"      "ACT_DOTA_CAST_ABILITY_1"

    "precache"
    {
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_visage.vsndevts"
      "particle"  "particles/units/heroes/hero_visage/visage_grave_chill_tgt.vpcf"
    }

    "AbilityValues"
    {
      "move_slow"               "30"
      "attack_slow"             "30"
      "duration"                "15"
    }
  }

  // This unit deals 150% against buildings
  "flesh_golem_demolish"
  {
    "AbilityTextureName"          "lone_druid_spirit_bear_demolish"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/generic/demolish"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityValues"
    {
      "damage_pct"    "150"
    }
  }

  // Grants a 33% chance on attack to hit all enemies in 150 range for
  // 125 damage and all units in 250 range for half damage.
  "flesh_golem_pulverize"
  {
    "AbilityTextureName"          "undying_decay"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/generic/pulverize"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/econ/items/undying/undying_pale_augur/undying_pale_augur_decay.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_undying.vsndevts"
    }

    "AbilityValues"
    {
      "chance"        "33"
      "close_range"   "150"
      "close_damage"  "125"
      "far_range"     "250"
      "far_damage"    "62.5"
    }
  }

  // All units hit get chilled for 5 seconds
  "frost_wyrm_chilling_attack"
  {
    "AbilityTextureName"          "winter_wyvern_arctic_burn"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/chilling_attack"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_abaddon/abaddon_frost_slow.vpcf"
    }

    "AbilityValues"
    {
      "duration"      "5"
      "move_slow"     "30"
      "attack_slow"   "30"
      "radius"        "250"
    }
  }

  // Increases nearby allies damage by 20%
  "skeleton_general_command_aura"
  {
    "AbilityTextureName"          "vengefulspirit_command_aura"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/undead/command_aura"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    "AbilityCastRange"            "900"

    "AbilityValues"
    {
      "radius"        "900"
      "damage_increase"      "20"
    }
  }

  "skeleton_warrior_bash"
  {
    "AbilityTextureName"          "roshan_bash"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/generic/bash"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    "AbilityUnitDamageType"       "DAMAGE_TYPE_MAGICAL"

    "AbilityValues"
    {
      "bash_duration"  "2"
      "bash_chance"    "15"
      "bash_damage"    "25"
    }
  }

  "skeleton_critical_strike"
  {
    "AbilityTextureName"            "skeleton_king_mortal_strike"
    "BaseClass"                     "ability_lua"
    "ScriptFile"                    "abilities/generic/critical_strike"
    "MaxLevel"                      "1"
    "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityValues"
    {
      "crit_chance"   "10"
      "crit_damage"   "200"
    }
  }

  "skeleton_evasion"
  {
    "AbilityTextureName"          "phantom_assassin_blur"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/generic/evasion"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityValues"
    {
      "evasion"                 "15"
    }
  }
}