"DOTAAbilities"
{
  // Lowers the armor of all enemies by 6
  "gaze_of_corruption"
  {
    "AbilityTextureName"          "medusa_stone_gaze"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/gaze_of_corruption"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                "FIELD_INTEGER"
        "armor"                   "-6"
      }
    }
  }

  // Creates 6 aggressive tentacles around a random enemy unit. raised tentacles
  // have a lesser critical strike
  "tentacle_prison"
  {
    "AbilityTextureName"          "venomancer_plague_ward"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/tentacle_prison"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
    "AbilityCooldown"             "1.0"
    "AbilityManaCost"             "15"
  }

  "tentacle_critical_strike"
  {
    "AbilityTextureName"            "lycan_summon_wolves_critical_strike"
    "BaseClass"                     "ability_lua"
    "ScriptFile"                    "abilities/generic/critical_strike"
    "MaxLevel"                      "1"
    "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"      "FIELD_INTEGER"
        "crit_chance"   "10"
      }
      "02"
      {
        "var_type"      "FIELD_INTEGER"
        "crit_damage"   "200"
      }
    }
  }

  // Deals 200 damage to a random enemy.
  "touch_of_pain"
  {
    "AbilityTextureName"          "lion_finger_of_death"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/touch_of_pain"
    "MaxLevel"                    "1"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_lion/lion_spell_finger_of_death.vpcf"
    }

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
    "AbilityCooldown"             "1.0"
    "AbilityManaCost"             "6"
  }

  "corrupted_weakening_attack"
  {
    "AbilityTextureName"          "bane_enfeeble"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/weakening_attack"
    "MaxLevel"                    "3"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_bane/bane_enfeeble.vpcf"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                "FIELD_INTEGER"
        "damage"                  "-27 -55 -100"
      }
      "02"
      {
        "var_type"                "FIELD_INTEGER"
        "duration"                "3"
      }
    }
  }

  "corrupted_treant_cleave"
  {
    "AbilityTextureName"          "sven_great_cleave"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/generic/cleave"
    "MaxLevel"                    "3"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_sven/sven_spell_great_cleave.vpcf"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"              "FIELD_INTEGER"
        "cleave_damage"         "0 25 40"
      }
      "02"
      {
        "var_type"              "FIELD_INTEGER"
        "cleave_radius"         "200"
      }
    }
  }

  "corrupted_treant_critical_strike"
  {
    "AbilityTextureName"            "lycan_summon_wolves_critical_strike"
    "BaseClass"                     "ability_lua"
    "ScriptFile"                    "abilities/generic/critical_strike"
    "MaxLevel"                      "3"
    "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"      "FIELD_INTEGER"
        "crit_chance"   "0 10 15"
      }
      "02"
      {
        "var_type"      "FIELD_INTEGER"
        "crit_damage"   "200"
      }
    }
  }

  "fan_of_spikes"
  {
    "AbilityTextureName"          "nyx_assassin_impale"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/fan_of_spikes"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
    "AbilityUnitTargetTeam"       "DOTA_UNIT_TARGET_TEAM_ENEMY"
    "AbilityUnitTargetType"       "DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"

    "AbilityCooldown"             "15.0"
    "AbilityManaCost"             "40"

    "AbilityCastRange"        "700"
    "AbilityCastPoint"        "0.4"
    "AbilityCastAnimation"    "ACT_DOTA_CAST_ABILITY_1"
    "AbilitySound"            "Hero_NyxAssassin.Impale"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_nyx_assassin/nyx_assassin_impale.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_nyx_assassin.vsndevts"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"      "FIELD_INTEGER"
        "width"         "125"
      }
      "02"
      {
        "var_type"      "FIELD_FLOAT"
        "duration"      "3.5"
      }
      "03"
      {
        "var_type"      "FIELD_INTEGER"
        "length"        "900"
      }
      "04"
      {
        "var_type"      "FIELD_INTEGER"
        "speed"         "1600"
      }
      "05"
      {
        "var_type"      "FIELD_INTEGER"
        "damage"        "250"
      }
    }
  }

  // (+7 dmg per hit) if the target dies, it explodes, dealing
  // 80 spell damage to enemies in 150 aoe and half in 200 aoe
  "void_walker_incinerate"
  {
    "AbilityTextureName"          "spawnlord_master_stomp"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/incinerate"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_enigma/enigma_malefice.vpcf"
      "particle"  "particles/econ/events/ti9/blink_dagger_ti9_end.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_alchemist.vsndevts"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                "FIELD_INTEGER"
        "damage_per_hit"          "7"
      }
      "02"
      {
        "var_type"                "FIELD_INTEGER"
        "explode_damage"          "80 160"
      }
      "03"
      {
        "var_type"                "FIELD_INTEGER"
        "full_aoe"                "150"
      }
      "04"
      {
        "var_type"                "FIELD_INTEGER"
        "half_aoe"                "200"
      }
    }
  }

  "void_walker_corruption_aura"
  {
    "AbilityTextureName"          "enigma_midnight_pulse"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/corruption_aura"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityCastRange"            "400 650"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                "FIELD_INTEGER"
        "armor"                   "-2 -4"
      }
      "02"
      {
        "var_type"                "FIELD_INTEGER"
        "radius"                  "400 650"
      }
    }
  }

  // deals less damage to further targets
  "nether_drake_splash_attack"
  {
    "AbilityTextureName"          "abaddon_death_coil"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/nether_drake_splash_attack"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_AUTOCAST | DOTA_ABILITY_BEHAVIOR_ATTACK"

    "AbilityManaCost"             "20"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_visage/visage_base_attack.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_visage.vsndevts"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                "FIELD_INTEGER"
        "bonus_damage"            "20 25"
      }
      "02"
      {
        "var_type"                "FIELD_INTEGER"
        "radius"                  "250"
      }
    }
  }

  "felhound_haste_aura"
  {
    "AbilityTextureName"          "spirit_breaker_empowering_haste"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/haste_aura"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityCastRange"            "900"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                "FIELD_INTEGER"
        "attack_speed"            "18"
      }
      "02"
      {
        "var_type"                "FIELD_INTEGER"
        "radius"                  "900"
      }
    }
  }

  // deals 100 damage to nearby units in 225 range. further targets take less damage
  "infernal_detonate"
  {
    "AbilityTextureName"          "techies_suicide"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/detonate"
    "MaxLevel"                    "2"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "AbilityCastRange"            "225 275"

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                "FIELD_INTEGER"
        "damage"                  "100 150"
      }
      "02"
      {
        "var_type"                "FIELD_INTEGER"
        "radius"                  "225 275"
      }
    }
  }

  // attacks do 60 additional damage to all units in a line
  "infernal_line_damage"
  {
    "AbilityTextureName"          "lion_impale"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/line_damage"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/units/heroes/hero_nyx_assassin/nyx_assassin_impale.vpcf"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                "FIELD_INTEGER"
        "damage"                  "60"
      }
      "02"
      {
        "var_type"                "FIELD_INTEGER"
        "radius"                  "200"
      }
    }
  }

  // 10% chance on each attack to take control of the attacked unit
  "incubus_overtake"
  {
    "AbilityTextureName"          "terrorblade_metamorphosis"
    "BaseClass"                   "ability_lua"
    "ScriptFile"                  "abilities/corrupted/overtake"
    "MaxLevel"                    "1"

    "AbilityBehavior"             "DOTA_ABILITY_BEHAVIOR_PASSIVE"

    "precache"
    {
      "particle"  "particles/econ/items/terrorblade/terrorblade_back_ti8/terrorblade_sunder_ti8.vpcf"
      "soundfile" "soundevents/game_sounds_heroes/game_sounds_terrorblade.vsndevts"
    }

    "AbilitySpecial"
    {
      "01"
      {
        "var_type"                "FIELD_INTEGER"
        "chance"                  "10"
      }
    }
  }
}