STARTING_GOLD = 250
STARTING_LUMBER = 125
STARTING_CHEESE = 1

POINTS_TO_WIN = 2

HERO_SELECT_TIME = 45
POST_ROUND_TIME = 10

STARTING_INCOME = 5
INCOME_TICK_RATE = 10

REPAIR_HEAL_RATE = 12

CORPSE_DURATION = 10
CORPSE_APPEAR_DELAY = 3

DRAW_VOTE_DELAY = 1000