STARTING_GOLD = 250
STARTING_LUMBER = 125
STARTING_CHEESE = 1

TIME_BEFORE_FIRST_ROUND = 5
HERO_SELECT_TIME = 45

STARTING_INCOME = 5
INCOME_TICK_RATE = 10

REPAIR_HEAL_RATE = 10

CORPSE_DURATION = 10
CORPSE_APPEAR_DELAY = 3