g_Precache_Tables = {
  npc_dota_hero_kunkka = {
    "npc_dota_hero_kunkka",    
    "barracks",
    "stronghold",
    "footman",
    "defender",
    "sniper_nest",
    "gunners_hall",
    "marksmens_encampment",
    "sniper",
    "heavy_gunner",
    "marksman",
    "weapon_lab",
    "mortar",
    "gryphon_rock",
    "gryphon_rider",
    "chapel",
    "church",
    "crusader",
    "paladin",
    "hjordhejmen",
    "warlock",
    "gjallarhorn",
    "artillery",
    "watch_tower",
    "heroic_shrine",    
  },

  npc_dota_hero_slark = {
    "npc_dota_hero_slark",
    -- Buildings
    "murloc_hut",
    "murloc_camp",
    "murloc_village",
    "murloc_fortress",
    "swamp_well",
    "lernaean_fountain",
    "temple_of_snakes",
    "spawning_grounds",
    "royal_spawning_grounds",
    "reptile_pool",
    "naga_spring",
    "ancient_pyramid",
    "oracle_of_sirens",
    "coral_statue",
    "tidal_guardian",
    -- Units
    "murloc",
    "murloc_warrior",
    "murloc_champion",
    "murloc_assassin",
    "suupmolk",
    "ancient_hydra",
    "hydra",
    "lesser_hydra",
    "winged_serpent",
    "naga_guardian",
    "naga_guardian",
    "dragon_turtle",
    "naga_siren",
    "naga_lobster",
  },

  npc_dota_hero_abaddon = {
    "npc_dota_hero_abaddon",
    -- Buildings
    "rotting_hay_cart",
    "tainted_farm",
    "defiled_granary",
    "temple_of_bone",
    "temple_of_necromancy",
    "high_citadel_of_necromancy",
    "crypt",
    "graveyard",
    "haunted_mine",
    "slaughter_house",
    "dragon_cemetary",
    "death_pit",
    "skull_pile",
    "skull_shrine",
    "turret_of_souls",
    "city_of_decay",
    -- Units
    "zombie",
    "suffocated_zombie",
    "plague_bearer",
    "necromancer",
    "mighty_necromancer",
    "lich_king",
    "vampire",
    "lesser_vampire",
    "vampire_lord",
    "banshee",
    "flesh_golem",
    "frost_wyrm",
    "skeletal_mage",
    "greater_skeletal_mage",
    "skeleton_archer",
    "greater_skeleton_archer",
    "skeleton_warrior",
    "greater_skeleton_warrior",
    "skeleton_hero",
    "skeleton_general",
  },

  npc_dota_hero_vengefulspirit = {
    "npc_dota_hero_vengefulspirit",
    -- Buildings
    "hunters_hall",
    "rangers_hall",
    "amazons_hall",
    "moon_shrine",
    "moon_altar",
    "house_of_shadows",
    "guild_of_shadows",
    "pillaged_hut",
    "scorched_mansion",
    "fountain_of_wonders",
    "nightelf_siege_factory",
    "silver_glade",
    "obelisk_of_wilderness",
    "elunes_lantern",
    "starfall_obelisk",
    -- Units
    "hunter",
    "ranger",
    "amazon",
    "druid",
    "sage_druid",
    "assassin",
    "royal_assassin",
    "avenging_spirit",
    "avatar_of_vengeance",
    "faerie_dragon",
    "glaive_thrower",
  },

  npc_dota_hero_treant = {
    "npc_dota_hero_treant",
    -- Buildings
    "spider_egg_clutch",
    "spider_egg_nest",
    "spider_egg_hatchery",
    "furbolg_hut",
    "furbolg_abode",
    "ancient_of_growth",
    "ancient_of_life",
    "ancient_of_eternity",
    "ancient_of_slumber",
    "ancient_of_hibernation",
    "emerald_dragon_roost",
    "monolith",
    "ancient_guardian",
    "ancient_protector",
    "ancient_of_wind",
    "ancient_of_wonders",
    -- Units
    "black_spider",
    "giant_spider",
    "brood_mother",
    "furbolg_shaman",
    "furbolg_shaman",
    "dryad",
    "keeper_of_the_grove",
    "ancient_keeper",
    "emerald_dragon",
    "bear",
    "ancient_bear",
    "mountain_giant",
    "keeper_treant",
  },

  npc_dota_hero_juggernaut = {
    "npc_dota_hero_juggernaut",
    -- Buildings
    "fighters_hall",
    "advanced_fighters_hall",
    "superior_fighters_hall",
    "shamanic_tent",
    "troll_hut",
    "trappers_hut",
    "falcon_clan_encampment",
    "kodo_farm",
    "offensive_kodo_farm",
    "defensive_kodo_farm",
    "spellbreaker_kodo_farm",
    "orcish_siege_factory",
    "serpent_rock",
    "ceremonial_totem",
    "anti_air_tower",
    "stasis_totem",
    -- Units
    "grunt",
    "veteran_grunt",
    "axemaster",
    "shaman",
    "troll",
    "troll_trapper",
    "wyvern_rider",
    "kodo",
    "offensive_kodo",
    "defensive_kodo",
    "spellbreaker_kodo",
    "catapult",
  },

  npc_dota_hero_tusk = {
    "npc_dota_hero_tusk",
    -- Buildings
    "snowy_rocks",
    "icy_rocks",
    "glacier",
    "igloo",
    "ice_troll_hut",
    "ice_troll_voodoo_hut",
    "ice_claws",
    "frost_claws",
    "azure_nest",
    "crystal_palace",
    "frost_launcher",
    "greater_frost_launcher",
    "chilling_mushroom",
    "icy_tower",
    "world_freezer",
    -- Units
    "frost_wolf",
    "polar_bear",
    "magnataur",
    "hrimthrusa",
    "troll_shadow_priest",
    "ice_troll_witch_doctor",
    "wendigo",
    "ancient_wendigo",
    "azure_drake",
    "ice_queen",
  },

  npc_dota_hero_invoker = {
    "npc_dota_hero_invoker",
    -- Buildings
    "archery_range",
    "archery_tower",
    "hall_of_honor",
    "hall_of_the_eldest",
    "bloodelf_war_academy",
    "dragonhawk_portal",
    "highelf_siege_factory",
    "school_of_wizardry",
    "tower_of_supreme_magic",
    "city_of_magic",
    "obelisk_of_light",
    "arcane_tower",
    "golden_shrine_of_justice",
    -- Units
    "archer",
    "master_archer",
    "blademaster",
    "elder_blademaster",
    "bloodthirster",
    "dragonhawk_rider",
    "siege_ballista",
    "sorceress",
    "wizard",
  },

  npc_dota_hero_grimstroke = {
    "npc_dota_hero_grimstroke",
    -- Buildings
    "corrupted_ancient_of_battle",
    "corrupted_ancient_of_war",
    "corrupted_ancient_of_annihilation",
    "void_portal",
    "portal_of_the_abyss",
    "nether_ancient",
    "shadow_ancient",
    "felhound_shrine",
    "hells_gate",
    "hells_portal",
    "demonic_statue",
    "well_of_pain",
    "forgotten_one",
    "corrupted_protector",
    "eye_of_corruption",
    -- Units
    "corrupted_ent",
    "corrupted_treant",
    "corrupted_annihilator",
    "void_walker",
    "void_keeper",
    "nether_drake",
    "shadow_drake",
    "felhound",
    "infernal_machine",
    "infernal_tank",
    "incubus",
    "tentacle_prison_tentacle",
  },
  
  npc_dota_hero_chaos_knight = {
    "npc_dota_hero_chaos_knight",
    -- Buildings
    "lesser_demon_cage",
    "greater_demon_cage",
    "chaos_citadel",
    "greater_chaos_citadel",
    "altar_of_greed",
    "fountain_of_blood",
    "dragon_nest",
    "demon_gate",
    "eraser_1",
    "eraser_2",
    "eraser_3",
    "volcano",
    "magic_tower_ruin",
    "shrine_of_destruction",
    -- Units
    "satyr",
    "quill_demon",
    "chaos_warrior",
    "chaos_champion",
    "succubus",
    "blood_fiend",
    "red_dragon",
    "infernal",
    "mutation",
  },

  npc_dota_hero_tinker = {
    "npc_dota_hero_tinker",
    -- Buildings
    "aircraft_factory",
    "bomber_factory",
    "tank_factory",
    "heavy_tank_factory",
    "rocket_tank_factory",
    "assault_tank_factory",
    "mine_layer_factory",
    "demolition_lab",
    "gun_smith",
    "arsenal",
    "golem_factory",
    "precious_golem_factory",
    "lumber_mill",
    "power_plant",
    "spare_part_heap",
    "energy_tower",
    "blue_shield_generator",
    "red_shield_generator",
    -- Units
    "roterothopter",
    "gyrocopter",
    "light_tank",
    "heavy_tank",
    "rocket_tank",
    "assault_tank",
    "mine_layer",
    "lunatic_goblin",
    "flame_gunner",
    "flamegunner_sergeant",
    "iron_golem",
    "adamant_golem",
    "goblin_shredder",
    "gobbo_mechanist",
  },

  npc_dota_hero_wisp = {
    "npc_dota_hero_wisp",
    -- Buildings
    "trapped_gale",
    "monument_of_wind_stream",
    "zephyros_memorial",
    "water_spring",
    "golden_fountain",
    "spellbound_fountain",
    "pillar_of_globe_lightning",
    "pillar_of_elmo_fire",
    "altar_of_fire",
    "altar_of_blaze",
    "tower_of_elder_knowledge",
    "rock_pile",
    "greater_fissure",
    "mana_generator",
    "obelisk_of_element",
    "book_of_conjuration",
    "elemental_guard_tower",
    "linker",
    -- Units
    "lesser_wind_elemental",
    "wind_elemental",
    "greater_wind_elemental",
    "lesser_water_elemental",
    "water_elemental",
    "greater_water_elemental",
    "lightning_elemental",
    "greater_lightning_elemental",
    "fire_elemental",
    "greater_fire_elemental",
    "master_of_elements",
    "earth_elemental",
    "greater_earth_elemental",
  },
}